/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RoutineId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Routine = IDL.Record({
  'id' : RoutineId,
  'isCompleted' : IDL.Bool,
  'scheduledTime' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
});

export const idlService = IDL.Service({
  'addRoutine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [RoutineId], []),
  'deleteRoutine' : IDL.Func([RoutineId], [], []),
  'editRoutine' : IDL.Func([RoutineId, IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
  'getRoutine' : IDL.Func([RoutineId], [Routine], ['query']),
  'markRoutineCompleted' : IDL.Func([RoutineId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RoutineId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Routine = IDL.Record({
    'id' : RoutineId,
    'isCompleted' : IDL.Bool,
    'scheduledTime' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
  });
  
  return IDL.Service({
    'addRoutine' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [RoutineId], []),
    'deleteRoutine' : IDL.Func([RoutineId], [], []),
    'editRoutine' : IDL.Func([RoutineId, IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
    'getRoutine' : IDL.Func([RoutineId], [Routine], ['query']),
    'markRoutineCompleted' : IDL.Func([RoutineId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };